spring:
  application:
    name: ecommerce

  redis:
    #host: localhost
    host: redis
    port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 6000ms

  flyway:
    enabled: true
    fail-on-unsupported-database: false
    baseline-on-migrate: true
    locations: classpath:db/migration

  datasource:
    #url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    #username: root
    #password: ""
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        #implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.lincoln4791: DEBUG
    io.jsonwebtoken: DEBUG
  file:
    name: logs/app.log

jwt:
  secret: XGg4pTbkuH2gvfn0ttzZji1hlwIs5fv8XCZFqUSM+mLHnDWiw+kUZYISUH5+xMPDQc2s0Dxx81oAVsZ2GRJI6A==
  expiration: 86400000

server:
  port: 8080
